[AppBundler]
app_summary = "Julia Distribution for Accelerator Physics Simulation"
windowed = false
overwrite_target = true
selfsign = true

juliaimg_mainless = true
juliaimg_incremental = true
juliaimg_precompile = true
